
"""Generic revision template for Alembic.

This template is used by alembic to create new migration files.
It defines `revision`, `down_revision`, `branch_labels` and `depends_on` and
includes `upgrade()` and `downgrade()` functions.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func


revision = 'a691267dd89f'
down_revision = 'b5006ac405bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('email', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
