
"""Generic revision template for Alembic.

This template is used by alembic to create new migration files.
It defines `revision`, `down_revision`, `branch_labels` and `depends_on` and
includes `upgrade()` and `downgrade()` functions.
"""


revision = 'b5006ac405bb'
down_revision = '36c9480b43ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
